### 1. Yeni Kullanıcı Kaydı (Register)
# Veritabanına şifrelenmiş kullanıcı ekler
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "username": "ali2",
  "password": "123"
}

###

### 2. Kullanıcı Girişi (Login)
# Şifreyi kontrol eder ve sana JWT Token döner
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "username": "ali2",
  "password": "123"
}

###

### 3. Misafir Listesini Getir (Kilitli Kapı)
# Buradaki 'Bearer'dan sonra gelen kısmı Login'den aldığın token ile değiştir!
GET http://localhost:8080/api/v1/guests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkyIiwiaWF0IjoxNzY5NTU3MDc4LCJleHAiOjE3Njk2NDM0Nzh9.FAsgVLe9-dO2AxbkKPQlIDKbvOYtrKOXTH6mLoOEXbM

###

### 4. Yeni Misafir Ekle (Güncellenmiş)
POST http://localhost:8080/api/v1/guests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkyIiwiaWF0IjoxNzY5NTU3MDc4LCJleHAiOjE3Njk2NDM0Nzh9.FAsgVLe9-dO2AxbkKPQlIDKbvOYtrKOXTH6mLoOEXbM

{
  "firstName": "hasasn",
  "lastName": "Yılmaz",
  "identificationNumber": "12345678901",
  "email": "hakan@email.com",
  "phoneNumber": "5551112233",
  "birthDate": "1990-01-01"
}